<a href="https://colab.research.google.com/github/Tim3s/Machine-Learning-Study/blob/main/5_3_Ensemble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
wine = pd.read_csv('https://bit.ly/wine_csv_data')
data = wine.to_numpy()[:, :3]
target = wine.to_numpy()[:, 3]
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)

In [2]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(rf, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9973541965122431 0.8905151032797809


In [3]:
rf.fit(train_input, train_target)
print(rf.feature_importances_)

[0.23167441 0.50039841 0.26792718]


In [4]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
print(rf.oob_score_)

0.8934000384837406


In [5]:
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9974503966084433 0.8887848893166506


In [6]:
et.fit(train_input, train_target)
print(et.feature_importances_)

[0.20183568 0.52242907 0.27573525]


In [7]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(random_state=42)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.8881086892152563 0.8720430147331015


In [8]:
gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9464595437171814 0.8780082549788999


In [9]:
gb.fit(train_input, train_target)
print(gb.feature_importances_)

[0.15872278 0.68010884 0.16116839]


In [12]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier
hgb = HistGradientBoostingClassifier(random_state=42)
score = cross_validate(hgb, train_input, train_target, return_train_score=True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9464595437171814 0.8780082549788999


In [13]:
from sklearn.inspection import permutation_importance
hgb.fit(train_input, train_target)
result = permutation_importance(hgb, train_input, train_target, n_repeats=10, random_state=42, n_jobs=-1)
print(result.importances_mean)

[0.08876275 0.23438522 0.08027708]


In [14]:
result = permutation_importance(hgb, test_input, test_target, n_repeats=10, random_state=42, n_jobs=-1)
print(result.importances_mean)

[0.05969231 0.20238462 0.049     ]


In [15]:
hgb.score(test_input, test_target)

0.8723076923076923

In [17]:
from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method='hist', random_state=42)
scores = cross_validate(xgb, train_input, train_target, return_train_score=True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.8824322471423747 0.8726214185237284


In [19]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(random_state=42)
scores = cross_validate(lgb, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9338079582727165 0.8789710890649293


In [24]:
from sklearn.model_selection import GridSearchCV
hgb = HistGradientBoostingClassifier()
params = {'learning_rate': np.arange(0.01, 1, 0.01)}
gs = GridSearchCV(hgb, params, return_train_score=True, n_jobs=-1)
gs.fit(train_input, train_target)
print(gs.cv_results_)

{'mean_fit_time': array([0.5670742 , 0.58851323, 0.59049129, 0.58486118, 0.59219909,
       0.56195984, 0.57760925, 0.59874878, 0.56444573, 0.572158  ,
       0.56545262, 0.57576699, 0.57986279, 0.56570358, 0.5656508 ,
       0.56664391, 0.55916562, 0.54179888, 0.54810195, 0.54669642,
       0.55200171, 0.55576234, 0.56205864, 0.54609466, 0.53497663,
       0.55326042, 0.54242458, 0.56074123, 0.53291745, 0.53112464,
       0.55207419, 0.52814569, 0.533359  , 0.52206297, 0.54500594,
       0.53552175, 0.52506108, 0.52353554, 0.52070637, 0.51762176,
       0.52284079, 0.52155609, 0.53522406, 0.52156029, 0.52082219,
       0.5353611 , 0.513873  , 0.53835931, 0.52758327, 0.53747597,
       0.51557069, 0.50506167, 0.53730021, 0.51524014, 0.51859531,
       0.52562642, 0.5312242 , 0.53054233, 0.51510348, 0.52723064,
       0.53428111, 0.52063007, 0.532195  , 0.53816752, 0.52284122,
       0.50927911, 0.50651522, 0.53441401, 0.51867313, 0.53790302,
       0.51573014, 0.51682963, 0.53581071, 0

In [25]:
print(gs.best_params_)

{'learning_rate': 0.31}


In [27]:
hgb = gs.best_estimator_
# hgb.max_iter = 1000
hgb.fit(train_input, train_target)
print(hgb.score(train_input, train_target), hgb.score(test_input, test_target))

0.996921300750433 0.8592307692307692
